[font]
name = "JetBrainsMono-Regular"

[prompt]
position = "bottom"
precision = 10
width = 550
builtins = false
radius = 0.1

[window]
quit-on = "quit"
position = "bottom"
pad-y = 120
fps = 120

[theme]
bg1 = 0x1f1d2ecc
bg2 = 0x26233aaa

fg1 = 0xe0def4ff
fg2 = 0x908caaff
fg3 = 0x6e6a86ff
